# -*- coding: utf-8 -*-
"""01_Category_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYUFSNHShXr41EZ4k5iFrZjSTgsgsn5z
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import pandas as pd
import pyarrow.parquet as pq

BASE_DIR = Path("/content/drive/MyDrive/CustomerPulse")
CLEAN_PARQUET_PATH = BASE_DIR / "data" / "processed" / "customerpulse_clean.parquet"
SAMPLES_DIR = BASE_DIR / "data" / "samples"
SAMPLES_DIR.mkdir(parents=True, exist_ok=True)

SAMPLE_100K_PATH = SAMPLES_DIR / "sample_100k.parquet"

print(CLEAN_PARQUET_PATH)

pf = pq.ParquetFile(CLEAN_PARQUET_PATH)

sample_parts = []
target_total = 100_000
per_batch_sample = 1500

for i, batch in enumerate(pf.iter_batches(batch_size=50_000)):
    batch_df = batch.to_pandas()

    n = min(per_batch_sample, len(batch_df))
    sampled = batch_df.sample(n=n, random_state=42 + i)

    sample_parts.append(sampled)

    collected = sum(len(x) for x in sample_parts)
    print(f"Batch {i+1} done | collected: {collected}")

    if collected >= target_total:
        break

sample_100k = pd.concat(sample_parts, ignore_index=True)

sample_100k = sample_100k.sample(
    n=100_000,
    random_state=42
).reset_index(drop=True)

sample_100k.to_parquet(SAMPLE_100K_PATH, index=False)

print("Saved 100K sample:")
print(SAMPLE_100K_PATH)
print(sample_100k.shape)

sample_100k["Product"].value_counts()

sample_100k.head()

# ==========================
# Standardize Product Labels
# ==========================

product_mapping = {
    "Credit reporting, credit repair services, or other personal consumer reports": "Credit reporting",
    "Credit reporting or other personal consumer reports": "Credit reporting",
    "Credit reporting": "Credit reporting",

    "Credit card or prepaid card": "Credit card / Prepaid card",
    "Credit card": "Credit card / Prepaid card",
    "Prepaid card": "Credit card / Prepaid card",

    "Payday loan, title loan, personal loan, or advance loan": "Payday / Personal loan",
    "Payday loan, title loan, or personal loan": "Payday / Personal loan",
    "Payday loan": "Payday / Personal loan",

    "Money transfer, virtual currency, or money service": "Money transfer / Virtual currency",
    "Money transfers": "Money transfer / Virtual currency",
    "Virtual currency": "Money transfer / Virtual currency",

    "Bank account or service": "Checking or savings account",
    "Consumer Loan": "Vehicle loan or lease",
}

sample_100k["Product_clean"] = sample_100k["Product"].replace(product_mapping)

sample_100k["Product_clean"].value_counts()

X = sample_100k["Consumer complaint narrative"]
y = sample_100k["Product_clean"]

# ==========================
# Final Product Label Standardization
# ==========================

product_mapping = {
    # Credit Reporting
    "Credit reporting": "Credit reporting",
    "Credit reporting or other personal consumer reports": "Credit reporting",
    "Credit reporting, credit repair services, or other personal consumer reports": "Credit reporting",

    # Credit Card
    "Credit card": "Credit card / Prepaid card",
    "Credit card or prepaid card": "Credit card / Prepaid card",
    "Prepaid card": "Credit card / Prepaid card",

    # Payday / Personal Loan
    "Payday loan": "Payday / Personal loan",
    "Payday loan, title loan, or personal loan": "Payday / Personal loan",
    "Payday loan, title loan, personal loan, or advance loan": "Payday / Personal loan",

    # Money Transfer
    "Money transfers": "Money transfer / Virtual currency",
    "Money transfer, virtual currency, or money service": "Money transfer / Virtual currency",
    "Virtual currency": "Money transfer / Virtual currency",

    # Bank Accounts
    "Bank account or service": "Checking or savings account",

    # Consumer Loan
    "Consumer Loan": "Vehicle loan or lease",

    # Rare Classes
    "Debt or credit management": "Other Financial Services",
    "Other financial service": "Other Financial Services",
}

sample_100k["Product_clean"] = (
    sample_100k["Product"]
    .replace(product_mapping)
)

print("Number of Classes:", sample_100k["Product_clean"].nunique())
print()

sample_100k["Product_clean"].value_counts()

import time
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, f1_score, classification_report

from pathlib import Path

BASE_DIR = Path("/content/drive/MyDrive/CustomerPulse")
SAMPLE_100K_PATH = BASE_DIR / "data" / "samples" / "sample_100k.parquet"

df = pd.read_parquet(SAMPLE_100K_PATH)

print(df.shape)
df.head()

X = df["Consumer complaint narrative"]
y = df["Product_clean"]

print("Total rows:", len(df))
print("Classes:", y.nunique())
print(y.value_counts())

# ==========================
# Recreate Product_clean
# ==========================

product_mapping = {
    "Credit reporting": "Credit reporting",
    "Credit reporting or other personal consumer reports": "Credit reporting",
    "Credit reporting, credit repair services, or other personal consumer reports": "Credit reporting",

    "Credit card": "Credit card / Prepaid card",
    "Credit card or prepaid card": "Credit card / Prepaid card",
    "Prepaid card": "Credit card / Prepaid card",

    "Payday loan": "Payday / Personal loan",
    "Payday loan, title loan, or personal loan": "Payday / Personal loan",
    "Payday loan, title loan, personal loan, or advance loan": "Payday / Personal loan",

    "Money transfers": "Money transfer / Virtual currency",
    "Money transfer, virtual currency, or money service": "Money transfer / Virtual currency",
    "Virtual currency": "Money transfer / Virtual currency",

    "Bank account or service": "Checking or savings account",
    "Consumer Loan": "Vehicle loan or lease",

    "Debt or credit management": "Other Financial Services",
    "Other financial service": "Other Financial Services",
}

df["Product_clean"] = df["Product"].replace(product_mapping)

df.to_parquet(SAMPLE_100K_PATH, index=False)

print("Product_clean created and saved.")
print(df["Product_clean"].value_counts())

X = df["Consumer complaint narrative"]
y = df["Product_clean"]

print("Total rows:", len(df))
print("Classes:", y.nunique())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

logreg_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=30000,
        ngram_range=(1, 2),
        min_df=3,
        max_df=0.9
    )),
    ("clf", LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        n_jobs=-1
    ))
])

start = time.time()

logreg_model.fit(X_train, y_train)

train_time = time.time() - start

print(f"Training completed in {train_time:.2f} seconds")

start = time.time()

y_pred = logreg_model.predict(X_test)

pred_time = time.time() - start

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))
print("Weighted F1:", f1_score(y_test, y_pred, average="weighted"))
print("Prediction Time:", pred_time)

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# ==========================
# Experiment Results Tracker
# ==========================

experiment_results = []

def log_results(model_name,
                accuracy,
                macro_f1,
                weighted_f1,
                train_time,
                prediction_time):

    experiment_results.append({
        "Model": model_name,
        "Accuracy": round(accuracy, 4),
        "Macro F1": round(macro_f1, 4),
        "Weighted F1": round(weighted_f1, 4),
        "Train Time (s)": round(train_time, 2),
        "Prediction Time (s)": round(prediction_time, 2)
    })

log_results(
    model_name="Logistic Regression",
    accuracy=accuracy_score(y_test, y_pred),
    macro_f1=f1_score(y_test, y_pred, average="macro"),
    weighted_f1=f1_score(y_test, y_pred, average="weighted"),
    train_time=train_time,
    prediction_time=pred_time
)

pd.DataFrame(experiment_results)

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

def train_and_evaluate(model, model_name):

    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(
            max_features=30000,
            ngram_range=(1,2),
            min_df=3,
            max_df=0.9
        )),
        ("classifier", model)
    ])

    # Training
    start = time.time()
    pipeline.fit(X_train, y_train)
    train_time = time.time() - start

    # Prediction
    start = time.time()
    predictions = pipeline.predict(X_test)
    prediction_time = time.time() - start

    # Metrics
    accuracy = accuracy_score(y_test, predictions)
    macro_f1 = f1_score(y_test, predictions, average="macro")
    weighted_f1 = f1_score(y_test, predictions, average="weighted")

    print("="*70)
    print(model_name)
    print("="*70)

    print(f"Accuracy      : {accuracy:.4f}")
    print(f"Macro F1      : {macro_f1:.4f}")
    print(f"Weighted F1   : {weighted_f1:.4f}")
    print(f"Train Time    : {train_time:.2f} sec")
    print(f"Predict Time  : {prediction_time:.2f} sec")

    print("\nClassification Report\n")
    print(classification_report(y_test, predictions))

    log_results(
        model_name,
        accuracy,
        macro_f1,
        weighted_f1,
        train_time,
        prediction_time
    )

    return pipeline

from sklearn.svm import LinearSVC

svm_model = train_and_evaluate(
    LinearSVC(
        class_weight="balanced",
        random_state=42
    ),
    "Linear SVM"
)

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1,2),
    min_df=3,
    max_df=0.9
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Train Shape :", X_train_tfidf.shape)
print("Test Shape  :", X_test_tfidf.shape)

from sklearn.metrics import accuracy_score, f1_score, classification_report

def evaluate_model(model, model_name):

    start = time.time()
    model.fit(X_train_tfidf, y_train)
    train_time = time.time() - start

    start = time.time()
    predictions = model.predict(X_test_tfidf)
    prediction_time = time.time() - start

    accuracy = accuracy_score(y_test, predictions)
    macro_f1 = f1_score(y_test, predictions, average="macro")
    weighted_f1 = f1_score(y_test, predictions, average="weighted")

    print("="*70)
    print(model_name)
    print("="*70)
    print(f"Accuracy      : {accuracy:.4f}")
    print(f"Macro F1      : {macro_f1:.4f}")
    print(f"Weighted F1   : {weighted_f1:.4f}")
    print(f"Train Time    : {train_time:.2f} sec")
    print(f"Predict Time  : {prediction_time:.2f} sec")

    log_results(
        model_name,
        accuracy,
        macro_f1,
        weighted_f1,
        train_time,
        prediction_time
    )

    print("\nClassification Report\n")
    print(classification_report(y_test, predictions))

    return model

from sklearn.naive_bayes import MultinomialNB

nb_model = evaluate_model(
    MultinomialNB(),
    "Multinomial Naive Bayes"
)

from sklearn.linear_model import SGDClassifier

sgd_svm_model = evaluate_model(
    SGDClassifier(
        loss="hinge",
        class_weight="balanced",
        max_iter=1000,
        random_state=42,
        n_jobs=-1
    ),
    "SGD Linear SVM"
)

# !pip -q install lightgbm

from lightgbm import LGBMClassifier

lgbm_model = evaluate_model(
    LGBMClassifier(
        n_estimators=300,
        learning_rate=0.05,
        num_leaves=31,
        random_state=42,
        n_jobs=-1,
        class_weight="balanced"
    ),
    "LightGBM"
)

df["combined_text"] = (
    df["Sub-product"].fillna("") + " " +
    df["Issue"].fillna("") + " " +
    df["Sub-issue"].fillna("") + " " +
    df["Consumer complaint narrative"].fillna("")
)

X = df["combined_text"]
y = df["Product_clean"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ==========================
# TF-IDF for Combined Text
# ==========================

vectorizer_combined = TfidfVectorizer(
    max_features=50000,
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.9
)

X_train_tfidf_combined = vectorizer_combined.fit_transform(X_train)
X_test_tfidf_combined = vectorizer_combined.transform(X_test)

print("Train:", X_train_tfidf_combined.shape)
print("Test:", X_test_tfidf_combined.shape)

# ==========================
# Linear SVM on Combined Text
# ==========================

from sklearn.svm import LinearSVC

start = time.time()

combined_svm = LinearSVC(
    class_weight="balanced",
    random_state=42
)

combined_svm.fit(X_train_tfidf_combined, y_train)

train_time = time.time() - start

start = time.time()
predictions = combined_svm.predict(X_test_tfidf_combined)
prediction_time = time.time() - start

accuracy = accuracy_score(y_test, predictions)
macro_f1 = f1_score(y_test, predictions, average="macro")
weighted_f1 = f1_score(y_test, predictions, average="weighted")

print("Accuracy:", accuracy)
print("Macro F1:", macro_f1)
print("Weighted F1:", weighted_f1)
print("Train Time:", train_time)
print("Prediction Time:", prediction_time)

print(classification_report(y_test, predictions))

from sklearn.svm import LinearSVC

svm_c05 = evaluate_model(
    LinearSVC(
        C=0.5,
        class_weight="balanced",
        random_state=42
    ),
    "Linear SVM (C=0.5)"
)

svm_c2 = evaluate_model(
    LinearSVC(
        C=2.0,
        class_weight="balanced",
        random_state=42
    ),
    "Linear SVM (C=2.0)"
)

svm_c5 = evaluate_model(
    LinearSVC(
        C=5.0,
        class_weight="balanced",
        random_state=42
    ),
    "Linear SVM (C=5.0)"
)

# ==========================
# Final Category Model Training + Export
# ==========================

import json
import joblib
import time
from pathlib import Path

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

MODEL_DIR = Path("/content/drive/MyDrive/CustomerPulse/models/category")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

final_category_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=30000,
        ngram_range=(1, 2),
        min_df=3,
        max_df=0.9
    )),
    ("classifier", LinearSVC(
        C=0.5,
        class_weight="balanced",
        random_state=42
    ))
])

X_full = df["Consumer complaint narrative"]
y_full = df["Product_clean"]

start = time.time()
final_category_model.fit(X_full, y_full)
train_time = time.time() - start

MODEL_PATH = MODEL_DIR / "category_classifier_svm.joblib"

joblib.dump(final_category_model, MODEL_PATH)

metadata = {
    "model_name": "Category Classification",
    "algorithm": "TF-IDF + Linear SVM",
    "training_rows": len(df),
    "classes": sorted(y_full.unique().tolist()),
    "best_validation_accuracy": 0.8756,
    "best_validation_macro_f1": 0.6924,
    "tfidf_max_features": 30000,
    "ngram_range": [1, 2],
    "svm_C": 0.5,
    "class_weight": "balanced",
    "train_time_seconds_full_100k": round(train_time, 2)
}

METADATA_PATH = MODEL_DIR / "category_metadata.json"

with open(METADATA_PATH, "w") as f:
    json.dump(metadata, f, indent=4)

print("Category model fully trained and exported.")
print("Model saved at:", MODEL_PATH)
print("Metadata saved at:", METADATA_PATH)
print("Training time:", round(train_time, 2), "seconds")

# ==========================
# Test Exported Category Model
# ==========================

loaded_model = joblib.load(MODEL_PATH)

sample_text = [
    "My credit report contains incorrect information and the company is not fixing it."
]

prediction = loaded_model.predict(sample_text)

print("Prediction:", prediction[0])

loaded_model = joblib.load(MODEL_PATH)

sample_text = [
    "My credit report contains incorrect information and the company is not fixing it.",
    "My mortgage payment was wrongly processed and I am being charged extra fees.",
    "A debt collector keeps calling me for a debt I do not owe."
]

predictions = loaded_model.predict(sample_text)

for text, pred in zip(sample_text, predictions):
    print("Text:", text)
    print("Predicted Category:", pred)
    print("-" * 50)

from sklearn.calibration import CalibratedClassifierCV
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib, json, time
from pathlib import Path

MODEL_DIR = Path("/content/drive/MyDrive/CustomerPulse/models/category")

calibrated_category_model = Pipeline([
    ("tfidf", TfidfVectorizer(
        max_features=30000,
        ngram_range=(1, 2),
        min_df=3,
        max_df=0.9
    )),
    ("classifier", CalibratedClassifierCV(
        estimator=LinearSVC(
            C=0.5,
            class_weight="balanced",
            random_state=42
        ),
        cv=3,
        method="sigmoid"
    ))
])

start = time.time()
calibrated_category_model.fit(X_full, y_full)
train_time = time.time() - start

CALIBRATED_MODEL_PATH = MODEL_DIR / "category_classifier_svm_calibrated.joblib"
joblib.dump(calibrated_category_model, CALIBRATED_MODEL_PATH)

print("Calibrated category model saved.")
print("Path:", CALIBRATED_MODEL_PATH)
print("Training time:", round(train_time, 2), "seconds")

loaded_calibrated_model = joblib.load(CALIBRATED_MODEL_PATH)

sample_text = [
    "My credit report contains incorrect information and the company is not fixing it.",
    "My mortgage payment was wrongly processed and I am being charged extra fees.",
    "A debt collector keeps calling me for a debt I do not owe."
]

predictions = loaded_calibrated_model.predict(sample_text)
probabilities = loaded_calibrated_model.predict_proba(sample_text)

for text, pred, probs in zip(sample_text, predictions, probabilities):
    confidence = probs.max()
    print("Text:", text)
    print("Category:", pred)
    print("Confidence:", round(confidence, 4))
    print("-" * 50)